SFML_VERSION = 2.6.1
SFML_SITE = $(call github,SFML,SFML,$(SFML_VERSION))
SFML_LICENSE = zlib
SFML_LICENSE_FILES = license.md
SFML_INSTALL_STAGING = YES
SFML_DEPENDENCIES = eudev mesa3d flac libvorbis openal freetype

SFML_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DSFML_BUILD_EXAMPLES=OFF \
	-DSFML_BUILD_DOC=OFF \
	-DSFML_BUILD_TEST_SUITE=OFF \
	-DSFML_USE_SYSTEM_DEPS=ON \
	-DSFML_USE_DRM=TRUE \
	-DOPENGL_ES=TRUE

$(eval $(cmake-package))
